---
all:
    data_dir: "../data/"        # Specify main data directory

ACE:
    binsize: 100000
    ploidies: ["2N","3N","4N","5N","squaremodel"]
    method: "RMSE"
    penalty: 0.5
    penploidy: 0.5
